baseURL = "https://somethinginterestinghere.com/"
languageCode = "en-ie"
title = "[Something Interesting Here]"
theme = "mainroad"

[author]
  name = "Shane Breatnach"
  bio = "He's just this guy, y'know?"
  avatar = "img/shane.jpg"

[Params]
  subtitle = "(maybe something about music, or sport, or computers?)"
  description = "Shane Breatnach's personal blog"
  readmore = true

[Params.widgets]
  search = true
  recent_articles = true
  recent_articles_num = 10
  categories = true
  tags = true
  tags_counter = false
  social_linkedin = "shane-breatnach-0392ba5"
  social_github = "sbreatnach"

[permalinks]
  post = "/:year/:month/:title/"