version: 2
jobs:
  build:
    docker:
      - image: sbreatnach/hugo-netlify:1.0.0
    steps:
      - checkout
      - run:
          name: Compile site
          command: hugo
      - run:
          name: Push site to Netlify
          command: netlifyctl deploy -y -A ${NETLIFY_TOKEN} -s ${SITE_ID} -b public/
          environment:
            SITE_ID: www.somethinginterestinghere.com
